//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.AI
{
    public static partial class AzureAIInferenceExtensions
    {
        public static IChatClient AsIChatClient(this global::Azure.AI.Inference.ChatCompletionsClient chatCompletionsClient, string? modelId = null) { throw null; }

        public static IEmbeddingGenerator<string, Embedding<float>> AsIEmbeddingGenerator(this global::Azure.AI.Inference.EmbeddingsClient embeddingsClient, string? defaultModelId = null, int? defaultModelDimensions = null) { throw null; }

        public static IEmbeddingGenerator<DataContent, Embedding<float>> AsIEmbeddingGenerator(this global::Azure.AI.Inference.ImageEmbeddingsClient imageEmbeddingsClient, string? defaultModelId = null, int? defaultModelDimensions = null) { throw null; }
    }
}