//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.Time.Testing
{
    public partial class FakeTimeProvider : System.TimeProvider
    {
        public FakeTimeProvider() { }

        public FakeTimeProvider(System.DateTimeOffset startDateTime) { }

        public System.TimeSpan AutoAdvanceAmount { get { throw null; } set { } }

        public override System.TimeZoneInfo LocalTimeZone { get { throw null; } }

        public System.DateTimeOffset Start { get { throw null; } }

        public override long TimestampFrequency { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.Experimental("EXTEXP0004", UrlFormat = "https://aka.ms/dotnet-extensions-warnings/{0}")]
        public void AdjustTime(System.DateTimeOffset value) { }

        public void Advance(System.TimeSpan delta) { }

        public override System.Threading.ITimer CreateTimer(System.Threading.TimerCallback callback, object? state, System.TimeSpan dueTime, System.TimeSpan period) { throw null; }

        public override long GetTimestamp() { throw null; }

        public override System.DateTimeOffset GetUtcNow() { throw null; }

        public void SetLocalTimeZone(System.TimeZoneInfo localTimeZone) { }

        public void SetUtcNow(System.DateTimeOffset value) { }

        public override string ToString() { throw null; }
    }
}