//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.AmbientMetadata
{
    public partial class ApplicationMetadata
    {
        [System.ComponentModel.DataAnnotations.Required]
        public string ApplicationName { get { throw null; } set { } }

        public string? BuildVersion { get { throw null; } set { } }

        public string? DeploymentRing { get { throw null; } set { } }

        [System.ComponentModel.DataAnnotations.Required]
        public string EnvironmentName { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Configuration
{
    public static partial class ApplicationMetadataConfigurationBuilderExtensions
    {
        public static IConfigurationBuilder AddApplicationMetadata(this IConfigurationBuilder builder, Hosting.IHostEnvironment hostEnvironment, string sectionName = "ambientmetadata:application") { throw null; }
    }
}

namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class ApplicationMetadataServiceCollectionExtensions
    {
        public static IServiceCollection AddApplicationMetadata(this IServiceCollection services, Configuration.IConfigurationSection section) { throw null; }

        public static IServiceCollection AddApplicationMetadata(this IServiceCollection services, System.Action<AmbientMetadata.ApplicationMetadata> configure) { throw null; }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class ApplicationMetadataHostBuilderExtensions
    {
        public static IHostBuilder UseApplicationMetadata(this IHostBuilder builder, string sectionName = "ambientmetadata:application") { throw null; }
    }
}