//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.AI
{
    public static partial class OpenAIClientExtensions
    {
        public static IChatClient AsIChatClient(this OpenAI.Assistants.AssistantClient assistantClient, string assistantId, string? threadId = null) { throw null; }

        public static IChatClient AsIChatClient(this OpenAI.Chat.ChatClient chatClient) { throw null; }

        public static IChatClient AsIChatClient(this OpenAI.Responses.OpenAIResponseClient responseClient) { throw null; }

        public static IEmbeddingGenerator<string, Embedding<float>> AsIEmbeddingGenerator(this OpenAI.Embeddings.EmbeddingClient embeddingClient, int? defaultModelDimensions = null) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("MEAI001")]
        public static ISpeechToTextClient AsISpeechToTextClient(this OpenAI.Audio.AudioClient audioClient) { throw null; }

        public static OpenAI.Assistants.FunctionToolDefinition AsOpenAIAssistantsFunctionToolDefinition(this AIFunction function) { throw null; }

        public static OpenAI.Chat.ChatTool AsOpenAIChatTool(this AIFunction function) { throw null; }

        public static OpenAI.Realtime.ConversationFunctionTool AsOpenAIConversationFunctionTool(this AIFunction function) { throw null; }

        public static OpenAI.Responses.ResponseTool AsOpenAIResponseTool(this AIFunction function) { throw null; }
    }
}