//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.Compliance.Redaction
{
    public sealed partial class ErasingRedactor : Redactor
    {
        public static ErasingRedactor Instance { get { throw null; } }

        public override int GetRedactedLength(System.ReadOnlySpan<char> input) { throw null; }

        public override int Redact(System.ReadOnlySpan<char> source, System.Span<char> destination) { throw null; }
    }

    public sealed partial class HmacRedactor : Redactor
    {
        public HmacRedactor(Options.IOptions<HmacRedactorOptions> options) { }

        public override int GetRedactedLength(System.ReadOnlySpan<char> input) { throw null; }

        public override int Redact(System.ReadOnlySpan<char> source, System.Span<char> destination) { throw null; }
    }

    public partial class HmacRedactorOptions
    {
        [System.Diagnostics.CodeAnalysis.StringSyntax("Base64")]
        [System.ComponentModel.DataAnnotations.Base64String]
        [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "Validating the Length attribute on a string does not require reflection, it is handled intrinsically.")]
        public string Key { get { throw null; } set { } }

        public int? KeyId { get { throw null; } set { } }
    }

    public static partial class RedactionExtensions
    {
        public static IRedactionBuilder SetHmacRedactor(this IRedactionBuilder builder, Configuration.IConfigurationSection section, params Classification.DataClassificationSet[] classifications) { throw null; }

        public static IRedactionBuilder SetHmacRedactor(this IRedactionBuilder builder, System.Action<HmacRedactorOptions> configure, params Classification.DataClassificationSet[] classifications) { throw null; }
    }
}

namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class RedactionServiceCollectionExtensions
    {
        public static IServiceCollection AddRedaction(this IServiceCollection services, System.Action<Compliance.Redaction.IRedactionBuilder> configure) { throw null; }

        public static IServiceCollection AddRedaction(this IServiceCollection services) { throw null; }
    }
}