//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.AspNetCore.Hosting
{
    public static partial class ServiceFakesWebHostExtensions
    {
        public static IWebHostBuilder ListenHttpOnAnyPort(this IWebHostBuilder builder) { throw null; }

        public static IWebHostBuilder ListenHttpsOnAnyPort(this IWebHostBuilder builder, System.Security.Cryptography.X509Certificates.X509Certificate2? sslCertificate = null) { throw null; }

        public static IWebHostBuilder UseFakeStartup(this IWebHostBuilder builder) { throw null; }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class ServiceFakesHostExtensions
    {
        public static System.Net.Http.HttpClient CreateClient(this IHost host, System.Net.Http.HttpMessageHandler? handler = null, System.Func<System.Uri, bool>? addressFilter = null) { throw null; }

        public static System.Collections.Generic.IEnumerable<System.Uri> GetListenUris(this IHost host) { throw null; }
    }
}