//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class ObjectPoolServiceCollectionExtensions
    {
        public static IServiceCollection AddPooled<TService>(this IServiceCollection services, System.Action<ObjectPool.DependencyInjectionPoolOptions>? configure = null)
            where TService : class { throw null; }

        public static IServiceCollection AddPooled<TService, TImplementation>(this IServiceCollection services, System.Action<ObjectPool.DependencyInjectionPoolOptions>? configure = null)
            where TService : class where TImplementation : class, TService { throw null; }

        public static IServiceCollection ConfigurePool<TService>(this IServiceCollection services, System.Action<ObjectPool.DependencyInjectionPoolOptions> configure)
            where TService : class { throw null; }

        public static IServiceCollection ConfigurePools(this IServiceCollection services, Configuration.IConfigurationSection section) { throw null; }
    }
}

namespace Microsoft.Extensions.ObjectPool
{
    public sealed partial class DependencyInjectionPoolOptions
    {
        public int Capacity { get { throw null; } set { } }
    }
}