//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class KubernetesProbesExtensions
    {
        public static IServiceCollection AddKubernetesProbes(this IServiceCollection services, Configuration.IConfigurationSection section) { throw null; }

        public static IServiceCollection AddKubernetesProbes(this IServiceCollection services, System.Action<Diagnostics.Probes.KubernetesProbesOptions> configure) { throw null; }

        public static IServiceCollection AddKubernetesProbes(this IServiceCollection services) { throw null; }
    }

    public static partial class TcpEndpointProbesExtensions
    {
        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services, Configuration.IConfigurationSection configurationSection) { throw null; }

        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services, System.Action<Diagnostics.Probes.TcpEndpointProbesOptions> configure) { throw null; }

        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services, string name, Configuration.IConfigurationSection configurationSection) { throw null; }

        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services, string name, System.Action<Diagnostics.Probes.TcpEndpointProbesOptions> configure) { throw null; }

        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services, string name) { throw null; }

        public static IServiceCollection AddTcpEndpointProbe(this IServiceCollection services) { throw null; }
    }
}

namespace Microsoft.Extensions.Diagnostics.Probes
{
    public partial class KubernetesProbesOptions
    {
        public TcpEndpointProbesOptions LivenessProbe { get { throw null; } set { } }

        public TcpEndpointProbesOptions ReadinessProbe { get { throw null; } set { } }

        public TcpEndpointProbesOptions StartupProbe { get { throw null; } set { } }
    }

    public static partial class ProbeTags
    {
        public const string Liveness = "_probe_liveness";
        public const string Readiness = "_probe_readiness";
        public const string Startup = "_probe_startup";
    }

    public partial class TcpEndpointProbesOptions
    {
        public System.Func<HealthChecks.HealthCheckRegistration, bool>? FilterChecks { get { throw null; } set { } }

        public System.TimeSpan HealthAssessmentPeriod { get { throw null; } set { } }

        [System.ComponentModel.DataAnnotations.Range(1, 10000)]
        public int MaxPendingConnections { get { throw null; } set { } }

        [System.ComponentModel.DataAnnotations.Range(1, 65535)]
        public int TcpPort { get { throw null; } set { } }
    }
}