//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class AsyncStateHttpContextExtensions
    {
        public static IServiceCollection AddAsyncStateHttpContext(this IServiceCollection services) { throw null; }
    }
}