//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class ResilienceServiceCollectionExtensions
    {
        public static IServiceCollection AddResilienceEnricher(this IServiceCollection services) { throw null; }
    }
}

namespace Polly
{
    public static partial class ResilienceContextExtensions
    {
        public static Microsoft.Extensions.Http.Diagnostics.RequestMetadata? GetRequestMetadata(this ResilienceContext context) { throw null; }

        public static void SetRequestMetadata(this ResilienceContext context, Microsoft.Extensions.Http.Diagnostics.RequestMetadata requestMetadata) { }
    }
}