//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class ResourceUtilizationHealthCheckExtensions
    {
        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, Configuration.IConfigurationSection section, System.Collections.Generic.IEnumerable<string> tags) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, Configuration.IConfigurationSection section, params string[] tags) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, Configuration.IConfigurationSection section) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, System.Action<Diagnostics.HealthChecks.ResourceUtilizationHealthCheckOptions> configure, System.Collections.Generic.IEnumerable<string> tags) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, System.Action<Diagnostics.HealthChecks.ResourceUtilizationHealthCheckOptions> configure, params string[] tags) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, System.Action<Diagnostics.HealthChecks.ResourceUtilizationHealthCheckOptions> configure) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, System.Collections.Generic.IEnumerable<string> tags) { throw null; }

        public static IHealthChecksBuilder AddResourceUtilizationHealthCheck(this IHealthChecksBuilder builder, params string[] tags) { throw null; }
    }
}

namespace Microsoft.Extensions.Diagnostics.HealthChecks
{
    public partial class ResourceUsageThresholds
    {
        [System.ComponentModel.DataAnnotations.Range(0, 100)]
        public double? DegradedUtilizationPercentage { get { throw null; } set { } }

        [System.ComponentModel.DataAnnotations.Range(0, 100)]
        public double? UnhealthyUtilizationPercentage { get { throw null; } set { } }
    }

    public partial class ResourceUtilizationHealthCheckOptions
    {
        [Options.ValidateObjectMembers]
        public ResourceUsageThresholds CpuThresholds { get { throw null; } set { } }

        [Options.ValidateObjectMembers]
        public ResourceUsageThresholds MemoryThresholds { get { throw null; } set { } }

        [System.Obsolete("This API is obsolete and will be removed in a future version. Consider using Resource Monitoring observable instruments.", DiagnosticId = "EXTOBS0001", UrlFormat = "https://aka.ms/dotnet-extensions-warnings/{0}")]
        public System.TimeSpan SamplingWindow { get { throw null; } set { } }

        [System.Diagnostics.CodeAnalysis.Experimental("EXTEXP0007", UrlFormat = "https://aka.ms/dotnet-extensions-warnings/{0}")]
        public bool UseObservableResourceMonitoringInstruments { get { throw null; } set { } }
    }
}