//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class CommonHealthChecksExtensions
    {
        public static IHealthChecksBuilder AddApplicationLifecycleHealthCheck(this IHealthChecksBuilder builder, System.Collections.Generic.IEnumerable<string> tags) { throw null; }

        public static IHealthChecksBuilder AddApplicationLifecycleHealthCheck(this IHealthChecksBuilder builder, params string[] tags) { throw null; }

        public static IHealthChecksBuilder AddManualHealthCheck(this IHealthChecksBuilder builder, System.Collections.Generic.IEnumerable<string> tags) { throw null; }

        public static IHealthChecksBuilder AddManualHealthCheck(this IHealthChecksBuilder builder, params string[] tags) { throw null; }

        public static IServiceCollection AddTelemetryHealthCheckPublisher(this IServiceCollection services, Configuration.IConfigurationSection section) { throw null; }

        public static IServiceCollection AddTelemetryHealthCheckPublisher(this IServiceCollection services, System.Action<Diagnostics.HealthChecks.TelemetryHealthCheckPublisherOptions> configure) { throw null; }

        public static IServiceCollection AddTelemetryHealthCheckPublisher(this IServiceCollection services) { throw null; }

        public static void ReportHealthy(this Diagnostics.HealthChecks.IManualHealthCheck manualHealthCheck) { }

        public static void ReportUnhealthy(this Diagnostics.HealthChecks.IManualHealthCheck manualHealthCheck, string reason) { }
    }
}

namespace Microsoft.Extensions.Diagnostics.HealthChecks
{
    public partial interface IManualHealthCheck : System.IDisposable
    {
        HealthCheckResult Result { get; set; }
    }

    public partial interface IManualHealthCheck<T> : IManualHealthCheck, System.IDisposable
    {
    }

    public partial class TelemetryHealthCheckPublisherOptions
    {
        public bool LogOnlyUnhealthy { get { throw null; } set { } }
    }
}